apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: delivery-dev

resources:
  - ../../../base/backend

namePrefix: dev-

images:
  - name: delivery-backend
    newName: delivery-backend
    newTag: dev-latest
