apiVersion: v1
kind: Service
metadata:
  name: media-service
  labels:
    app.kubernetes.io/name: media-service
    app.kubernetes.io/part-of: delivery-fullcycle
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    app.kubernetes.io/name: media-service
