apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: delivery-staging

resources:
  - ../../../base/frontend

namePrefix: staging-

patches:
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: delivery-frontend
    newName: 10.10.10.114:30000/ultragomosex/delivery-frontend
    newTag: staging-latest
