apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: delivery-dev

resources:
  - ../../../base/media-service

namePrefix: dev-

images:
  - name: delivery-media
    newName: 10.10.10.114:30000/ultragomosex/delivery-media
    newTag: dev-latest
