apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: delivery-prod

resources:
  - ../../../base/backend

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: delivery-backend
    newName: 10.10.10.114:30000/ultragomosex/delivery-backend
    newTag: v1.0.0
