apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: delivery-fullcycle
  source:
    repoURL: http://forgejo.forgejo.svc.cluster.local:3000/ultragomosex/delivery-fullcycle.git
    targetRevision: HEAD
    path: deploy/argocd/bootstrap/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
