name: Frontend CI & CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
    branches:
      - master
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t delivery-frontend:${IMAGE_TAG} -f frontend/Dockerfile frontend/
